### PR TITLE
Lookup tables in the package

### PR DESCRIPTION
**Pull request by nevrome**
I decided to move the lookup tables (db urls + version, thesauri) into the package as data objects. No more downloading from Github. With this change we do not need #122 and #125 any more.

This is a major interface change and we should increment the version number to 2.0.0, although many users will not feel any difference.

This PR also contains some minor changes to the getter and lookup functions as a consequence of the new data structure.

### CODE REVIEW

**Comment by nevrome** [comment]
@dirkseidensticker I implemented some major changes to simplify our work in the future. Maybe you could have a look.

**Review by dirkseidensticker — APPROVED** [review]
Looks good to me 🎱
Changes are especially useful with respect to the fact that R-universe build on the commits, thus the user would always get the latest version with each update

**Comment by nevrome** [comment]
Thanks for taking a look, Dirk! Btw. what's the point of the :8ball: emoji? Is there a deeper meaning? :bread: :laughing: ?

**Comment by dirkseidensticker** [comment]
🎱  simply refers to pocketing the 8-ball in pool billiard, thus winning the game ;)

**Pull request merged**
