### PR TITLE
IRDD

### PR DESCRIPTION
**Pull request by nevrome**
New database: https://sites.google.com/site/chapplearchaeology/download

### CODE REVIEW

**Comment by nevrome** [comment]
Could you please review, @dirkseidensticker? 

Unrelated: You mentioned that you have some code for an EUBAR (?) parser. Where can I find that code?

**Comment by dirkseidensticker** [comment]
I will test this tomorrow. Existing code of the EUBAR parser is in branch `dirk`; see https://github.com/ropensci/c14bazAAR/blob/dirk/R/get_eubar.R

**Comment by nevrome** [comment]
Excellent - thank you. Do you plan to finish this EUBAR code and/or prepare a separate PR for it?Probably you would have to cherry-pick the related commits.

**Comment by dirkseidensticker** [comment]
tested the IR-DD parser: works 🎱 - ready of be merged

**Comment by dirkseidensticker** [comment]
> Excellent - thank you. Do you plan to finish this EUBAR code and/or prepare a separate PR for it?Probably you would have to cherry-pick the related commits.

yeah, I can finish of the EUBAR parser

**Pull request merged**
