### PR TITLE
New Parser for MedAfriCarbon & Jomon Databases

### PR DESCRIPTION
**Pull request by dirkseidensticker**
Created new parsers for MedAfriCarbon & Crema Jomon Japan datasets (see #2 ).

*Known Issues:*
- [x] **MedAfriCarbon**
  - [get_medafricarbon.R#L35-L66](https://github.com/ropensci/c14bazAAR/blob/MedAfriCarbon%2BJomon/R/get_medafricarbon.R#L35-L66): Cultural attribution and references are listed in separate tables as individual entries within the original dataset.  The used **for()-loops impose quite a performance bottleneck**. How to do this better/faster?
- [x] **Jomon**
  - [x] [site = .data[["Site_Name_JP"]]](https://github.com/ropensci/c14bazAAR/blob/MedAfriCarbon%2BJomon/R/get_jomon.R#L27) used, but [encoding = "UTF-8"](https://github.com/ropensci/c14bazAAR/blob/MedAfriCarbon%2BJomon/R/get_jomon.R#L17) is not returning the desired output (only UTF-8 code). Checking the codes against [compart.com](https://www.compart.com/de/unicode/U+5C4B) shows that **characters are partially encoded as 'Han Chinese'**, which seems odd for data on Japan.
  - [x] **No coordinates** found in [data](https://github.com/ercrema/jomonPhasesAndPopulation/tree/master/data)-folder of original data set. Spatial differentiation seems only based on site names and province(?).
- [x] need to resolve merge-conflicts due to new branch being based on outdated [readme_overview_fig branch](https://github.com/ropensci/c14bazAAR/tree/readme_overview_fig)
- [x] Thesaurification failed, despite entering missing data in [thesauri](https://github.com/ropensci/c14bazAAR/blob/MedAfriCarbon%2BJomon/data-raw/material_thesaurus.csv)
Screenshot 2020-03-23 18 12 43

@nevrome : Any suggestion how to improve this?

### CODE REVIEW

**Comment by nevrome** [comment]
The Japanese characters look fine for me. At least as far as I can judge :smile:. Maybe a problem with your system?
image
It's ok if there are no coordinates. We already have other databases without these. Maybe @ercrema wants to comment this?

**Comment by nevrome** [comment]
Concerning the thesaurification: The reference tables are always downloaded from the master branch. `Ceramic Organic Residue` is in [here](https://github.com/ropensci/c14bazAAR/blob/MedAfriCarbon+Jomon/data-raw/material_thesaurus.csv), but not in [here](https://github.com/ropensci/c14bazAAR/blob/master/data-raw/material_thesaurus.csv) yet. This is a constant source of confusion and I'm more and more convinced that we have to find a better solution for this.

**Comment by dirkseidensticker** [comment]
> Concerning the thesaurification: The reference tables are always downloaded from the master branch. `Ceramic Organic Residue` is in [here](https://github.com/ropensci/c14bazAAR/blob/MedAfriCarbon+Jomon/data-raw/material_thesaurus.csv), but not in [here](https://github.com/ropensci/c14bazAAR/blob/master/data-raw/material_thesaurus.csv) yet. This is a constant source of confusion and I'm more and more convinced that we have to find a better solution for this.

Arg, damn ... you are so right ... okay

But ... please wait a second: please take a look at #96 ... there it seems the [country_thesaurus](https://github.com/ropensci/c14bazAAR/blob/master/data-raw/country_thesaurus) is not respected either

**Comment by dirkseidensticker** [comment]
> The Japanese characters look fine for me. At least as far as I can judge 😄. Maybe a problem with your system?
> image
> It's ok if there are no coordinates. We already have other databases without these. Maybe @ercrema wants to comment this?

Okay, actually same here, if I print into the console. But I always checked using `View()` and that only returns UTF-8 codes. But so this isn't an issue on our side 👍

**Comment by dirkseidensticker** [comment]
thanks for b282e40 ... I need to up my dplyr-game for sure

**Comment by ercrema** [comment]
The Japanese look fine - coordinates are a bit of nightmare for various reasons. We are working on a larger dataset which will have some coordinates but this is still work in progress. Thanks for adding both datasets on your package btw!

**Comment by dirkseidensticker** [comment]
a62bb76 adds variables missed in the initial parser and lists the unused variable in the reference list.

@nevrome please test if still functional, after that I can resolve merge conflicts & merge

**Comment by nevrome** [comment]
Great! Works fine. Go ahead!

**Comment by dirkseidensticker** [comment]
> The Japanese look fine - coordinates are a bit of nightmare for various reasons. We are working on a larger dataset which will have some coordinates but this is still work in progress. Thanks for adding both datasets on your package btw!

@ercrema many thanks for your explanations. Looking forward to future data ;)

**Pull request merged**
