### PR TITLE
Thesaurus update

### PR DESCRIPTION
**Pull request by nevrome**
Some updating and cleaning both of the lookup code and the thesaurus tables

### CODE REVIEW

**Comment by dirkseidensticker** [comment]
Saw a mismatch between the country_thesaurus and the changes made running `fix_database_country_name()` with aDRAC as test dataset:

Screenshot 2020-09-01 13 21 33

While the thesaurus lists CAR to be the Central African Republic, it gets attributed to Cameroon. Any idea? The thesaurus is correct.

**Comment by nevrome** [comment]
The thesaurus is downloaded from the master branch - same problem as with the database URLs. Please test with 

```
get_adrac() %>% classify_material(material_thesaurus = get_material_thesaurus("data-raw/material_thesaurus.csv"))
```

**Comment by dirkseidensticker** [comment]
> The thesaurus is downloaded from the master branch - same problem as with the database URLs. Please test with
> 
> ```
> get_adrac() %>% classify_material(material_thesaurus = get_material_thesaurus("data-raw/material_thesaurus.csv"))
> ```

Damn ... I should have known that. Works like a charm 🎱

**Review by dirkseidensticker — APPROVED** [review]
🎱

**Pull request merged**
