### PR TITLE
calpal update

### PR DESCRIPTION
**Pull request by nevrome**
Updated the CalPal database from version **2017_04_27** to **2020_08_20** and made some changes in the material thesaurus in that context

### CODE REVIEW

**Comment by nevrome** [comment]
Don't forget to manually set the database url when testing.

**Review by dirkseidensticker — APPROVED** [review]
Works fine 🎱

**Comment by dirkseidensticker** [comment]
Still with the new dataset I can see a few duplicates; especially from Dzhulyunica. Would you merge those or do you treat the datasset as is?

**Comment by nevrome** [comment]
Right - hm. In this case I could actually clean them, because I have control over the intermediate .tsv table. 

But I think it's better to report them to Bernie. He's the author of the database and if he wants he can fix them in the next version.

**Comment by dirkseidensticker** [comment]
based on a quick testing script; using the new tsv file

```r
a %>% 
  c14bazAAR::calibrate() %>% 
  c14bazAAR::remove_duplicates(mark_only = T) %>% 
  dplyr::filter(!is.na(duplicate_group))
b <- sort(unique(a$labnr))
```

I got this list of affected lab numbers. 

[doubles.txt](https://github.com/ropensci/c14bazAAR/files/5151219/doubles.txt)

Maybe you can cross-check this?

**Comment by nevrome** [comment]
I sent this duplicate list to Bernhard Weninger, the author of CalPal. He's aware and will remove them in the future.

**Pull request merged**
