### PR TITLE
Readme overview fig

### PR DESCRIPTION
**Pull request by dirkseidensticker**
I have added a (static) overview figure of the databases accessible through the c14bazAAR to the README: individual maps and a simple histogram of the uncalibrated ages.

@nevrome what do you think?

### CODE REVIEW

**Comment by nevrome** [comment]
I like the idea, @dirkseidensticker, but i don't like the fact that we then have to keep this figure updated. Also this `.Rmd` -> `.md` step is tedious. 

Maybe we could use this plot for the rOpenSci blog post that I will hopefully write one day?

**Comment by dirkseidensticker** [comment]
I actually like the fact that one could run the README.Rmd and check if all parsers work. Or do we have another test-script that can handle this?

But if you like you could close the PR and focus in the blogpost 😅

**Comment by dirkseidensticker** [comment]
@nevrome still keep the branch at the moment?

**Comment by nevrome** [comment]
Ja - sure. Maybe this code could become part of the plotting vignette or go somewhere else.

**Comment by dirkseidensticker** [comment]
Okay, guessed so :)

**Pull request closed without merging**
