### PR TITLE
switch from openxlsx to readxl & writexl

### PR DESCRIPTION
**Pull request by dirkseidensticker**
Updated parsers that rely on xlsx input data (`get_14cpalaeolithic()`, `get_14sea()`, `get_eubar()`, `get_irdd()`). Removed `openxlsx::read.xlsx()` with `readxl::read_excel()`.

One question: how is codemeta.json generated; manually or automatically? There openxlsx is still listed.

Had issue with the write `write_c14(. , format = "xlsx")` and tests failed on that stage.

@nevrome can you test and verify that the parsers work?

### CODE REVIEW

**Comment by nevrome** [comment]
Looks fine to me now :+1:

**Comment by nevrome** [comment]
Please remember to document all changes in the NEWS.md file. 

You don't have to do this with a PR now if you only edit the NEWS.md - feel free to push directly to the master.

**Comment by dirkseidensticker** [comment]
damn, you are right. sorry. will do after #112 is merged?

**Comment by nevrome** [comment]
Fair enough :+1:

**Pull request merged**
