### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by nevrome**
#80

### CODE REVIEW

**Comment by dirkseidensticker** [comment]
As briefly discussed my suggestion would be a logo with the street network of an actual bazar in the background (that one needs to navigate like one can navigate the various radiocarbon datasets out there using c14bazAAR). The background is the Kapalı Çarşı (Grand Bazaar) in IstaIstanbul and exported from OSM.

# TODO's
- [ ] find a better way to generate the coordinates for the icons (maybe no random generated one but fixed?)
- [ ] crop elements outside of the hexagon

@nevrome what do you think?

**Comment by nevrome** [comment]
The logo is the last major change for v.1.2.0. I think we can finalize the release when you're happy with it.

**Comment by dirkseidensticker** [comment]
I have converted the code to fixed geojson datasets generated in QGIS, only placement of which logo goes to what point is still randomized.

To me, v1.2.0 would be ready to release like that

**Comment by nevrome** [comment]
Excellent job, @dirkseidensticker. What do you think about my attempt to highlight the text a bit more?

**Comment by dirkseidensticker** [comment]
look's really good now, let's merge and release?

**Pull request merged**
